### PR TITLE
2020.5+fio Updates

### PR DESCRIPTION
**Pull request by doanac**
This gets a 2020.5+fio branch in place. The big difference between this and 2020.4+fio - A few of the "toup" patches have been proposed upstream. I've moved these to the first of the branch as "fromlist". We were able drop a clang formatting patch because it was fixed upstream. This means we have one less patch in 2020.5+fio than 2020.4+fio
 
Notable changes between 2020.4 and 2020.5:
 * get-garage-sign.py uses a new URL. This will affect OE builds but should "Just work".

The remaining changes were documentation, CI, and secondary support changes.

### CODE REVIEW

**Comment by doanac** [comment]
@ricardosalveti @mike-sul - this assumes that https://github.com/foundriesio/aktualizr/pull/32 gets merged as-is. otherwise, I'll reshuffle slightly

@mike-sul - this is our process for moving to new versions of actualizr. Basically - we've started running their $N-1 release. We rebase our out-of-tree patches onto this release.

**Comment by mike-sul** [comment]
Looks complicated at first glance. It would be great to learn the details of this process so I can take over it if you like.

**Comment by doanac** [comment]
Yes - it starts complex and then just becomes tedious. We are trying to shrink this patchset, but as you can see by looking at each patch - some (the ones with `fio extras`) will probably never make their way upstream unless we figure out a different way to accomplish the same goal. Lets chat soon in detail about this.

**Comment by doanac** [comment]
I forgot to include the "test plan". I'm doing in conjunction with the latest aktlite code:

# Test Plan Used

## Test aktualizr-get
**Run:**
~~~
LOG_STDERR=1 ./aktualizr-get -u https://ota-lite.foundries.io:8443/hub-creds/ 2>/dev/null
~~~
**Expect:** JSON output (stderr shouldn’t show up)

## Test check-in and server update
 1. Look at "last seen" value of `fioctl devices show rpi3-1`
 1. Run: `aktualizr-lite list`
    * Verify proper targets are listed
 1. Repeat step 1 and ensure timestamp has changed

## Test Update Mechanics
 1. Ensure aktualizr-lite daemon isn’t running
 1. Find 2 targets with the same ostree hash
 1. Run “aktualizr-lite update --update-name <older target>”
    * Run `fioctl devices updates list rpi3-1`. Verify the update to that build is the first entry.
    * Run `fioctl devices updates show rpi3-1 <update>`. Verify the events are there **except** for the "Completed" event.
 1. Reboot if needed
 1. Ensure containers are running for this target (proper hashes etc)
 1. Run `aktualizr-lite list`
    * Run display the update again in fioctl to verify its been marked completed.
    * Verify target name on the server has been updated
 1. Update to the newer target `aktualizr-lite update --update-name <newer target>`
 1. Run `aktualiz-lite list`
    * Verify step 7 updated the target name on the server
    * Verify `aktualizr-lite status` shows the correct target
 1. Ensure containers have been updated

## Test System and Hardware Info
Run: 
~~~
./aktualizr-lite daemon --loglevel 0  2>&1 | tee /tmp/tmp.log
~~~
and then look for calls to /system_info for network and hardware to succeed.

## Test Daemon
 1. Get device on an older target that will have an ostree hash difference with the latest
 1. Start aktualizr-lite: `systemctl start aktualizr-lite.`
    * In a few moments an update should start
    * It should reboot the system
    * While rebooting check ‘fioctl-device-show” to see its status shows as updating
 1. After reboot, ensure the device-status is now on the new target and the update-events include the "complete" event
 1. Add a new target (container only change build). Wait for aklite daemon to pick it up and install it.
    * Device shouldn’t reboot
    * Device status should show its on the new target
    * Containers should change
    * Update events should include the the “complete” event

## Failure Testing
 1. Stop aktualizr-lite daemon
 1. Add a bogus entry for ota-lite.foundries.io into /etc/hosts like:
    * 192.168.0.122 ota-lite.foundries.io
 1. Start the daemon.
    * It should log a “Refreshing target metadata”
    * It should hit errors talking to the server “Unable to update latest metadata”
    * It should sleep 10 seconds and try again
    * Remove the bogus entry from /etc/hosts
    * The next loop of the daemon should succeed in updating the target metadata.

**Review by mike-sul — APPROVED** [review]
@doanac LGTM, although I am not sure if I learned enough to be a decent reviewer here :).
I suppose I have to rebase my PR https://github.com/foundriesio/aktualizr/pull/34 with this branch as it should go into 2020.5+fio first of all?

**Review by ricardosalveti — APPROVED** [review]
LGTM, we can plan to land this in LMP after the next release, which should hopefully be released this week still.

**Pull request merged**
